---
- name: Install Tomcat
  hosts: all
  become: true
  tasks:
    - name: Install Tomcat
      apt:
        name: tomcat
        state: present
    - name: Start tomcat service
      service:
        name: tomcat
        state: started